
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.sovereignhorizon.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.sovereignhorizon.item.TotemofChanceItem;
import net.mcreator.sovereignhorizon.item.RecordSunriseItem;
import net.mcreator.sovereignhorizon.item.RawCorruptedFleshItem;
import net.mcreator.sovereignhorizon.item.LiquidVoidItem;
import net.mcreator.sovereignhorizon.item.ErrorPearlItem;
import net.mcreator.sovereignhorizon.item.ElixiteArmorItem;
import net.mcreator.sovereignhorizon.item.ElixisUpgradeSmithingTemplateItem;
import net.mcreator.sovereignhorizon.item.ElixisShardItem;
import net.mcreator.sovereignhorizon.item.CorruptedPearlItem;
import net.mcreator.sovereignhorizon.item.CookedCorruptedFleshItem;
import net.mcreator.sovereignhorizon.item.CatechismWingItem;
import net.mcreator.sovereignhorizon.item.BlueskinItem;
import net.mcreator.sovereignhorizon.item.BlueskinBootsItem;
import net.mcreator.sovereignhorizon.item.BinaryShardItem;
import net.mcreator.sovereignhorizon.item.AshyFleshItem;
import net.mcreator.sovereignhorizon.SovereignHorizonMod;

public class SovereignHorizonModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, SovereignHorizonMod.MODID);
	public static final RegistryObject<Item> TEST = block(SovereignHorizonModBlocks.TEST);
	public static final RegistryObject<Item> CATECHISM_SPAWN_EGG = REGISTRY.register("catechism_spawn_egg", () -> new ForgeSpawnEggItem(SovereignHorizonModEntities.CATECHISM, -10092442, -65281, new Item.Properties()));
	public static final RegistryObject<Item> SODALITE = block(SovereignHorizonModBlocks.SODALITE);
	public static final RegistryObject<Item> SODALITE_STAIRS = block(SovereignHorizonModBlocks.SODALITE_STAIRS);
	public static final RegistryObject<Item> SODALITE_SLAB = block(SovereignHorizonModBlocks.SODALITE_SLAB);
	public static final RegistryObject<Item> SODALITE_WALL = block(SovereignHorizonModBlocks.SODALITE_WALL);
	public static final RegistryObject<Item> SODALITE_PRESSURE_PLATE = block(SovereignHorizonModBlocks.SODALITE_PRESSURE_PLATE);
	public static final RegistryObject<Item> SODALITE_BUTTON = block(SovereignHorizonModBlocks.SODALITE_BUTTON);
	public static final RegistryObject<Item> SPARSE_DEEP_LICHEN_COVERED_SODALITE = block(SovereignHorizonModBlocks.SPARSE_DEEP_LICHEN_COVERED_SODALITE);
	public static final RegistryObject<Item> DEEP_LICHEN_COVERED_SODALITE = block(SovereignHorizonModBlocks.DEEP_LICHEN_COVERED_SODALITE);
	public static final RegistryObject<Item> COBBLED_SODALITE = block(SovereignHorizonModBlocks.COBBLED_SODALITE);
	public static final RegistryObject<Item> COBBLED_SODALITE_STAIRS = block(SovereignHorizonModBlocks.COBBLED_SODALITE_STAIRS);
	public static final RegistryObject<Item> COBBLED_SODALITE_SLAB = block(SovereignHorizonModBlocks.COBBLED_SODALITE_SLAB);
	public static final RegistryObject<Item> COBBLED_SODALITE_WALL = block(SovereignHorizonModBlocks.COBBLED_SODALITE_WALL);
	public static final RegistryObject<Item> POLISHED_SODALITE = block(SovereignHorizonModBlocks.POLISHED_SODALITE);
	public static final RegistryObject<Item> POLISHED_SODALITE_STAIRS = block(SovereignHorizonModBlocks.POLISHED_SODALITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_SODALITE_SLAB = block(SovereignHorizonModBlocks.POLISHED_SODALITE_SLAB);
	public static final RegistryObject<Item> POLISHED_SODALITE_WALL = block(SovereignHorizonModBlocks.POLISHED_SODALITE_WALL);
	public static final RegistryObject<Item> SODALITE_BRICKS = block(SovereignHorizonModBlocks.SODALITE_BRICKS);
	public static final RegistryObject<Item> SODALITE_BRICK_STAIRS = block(SovereignHorizonModBlocks.SODALITE_BRICK_STAIRS);
	public static final RegistryObject<Item> SODALITE_BRICK_SLAB = block(SovereignHorizonModBlocks.SODALITE_BRICK_SLAB);
	public static final RegistryObject<Item> SODALITE_BRICK_WALL = block(SovereignHorizonModBlocks.SODALITE_BRICK_WALL);
	public static final RegistryObject<Item> CRACKED_SODALITE_BRICKS = block(SovereignHorizonModBlocks.CRACKED_SODALITE_BRICKS);
	public static final RegistryObject<Item> SODALITE_TILES = block(SovereignHorizonModBlocks.SODALITE_TILES);
	public static final RegistryObject<Item> SODALITE_TILE_STAIRS = block(SovereignHorizonModBlocks.SODALITE_TILE_STAIRS);
	public static final RegistryObject<Item> SODALITE_TILE_SLAB = block(SovereignHorizonModBlocks.SODALITE_TILE_SLAB);
	public static final RegistryObject<Item> SODALITE_TILE_WALL = block(SovereignHorizonModBlocks.SODALITE_TILE_WALL);
	public static final RegistryObject<Item> CRACKED_SODALITE_TILES = block(SovereignHorizonModBlocks.CRACKED_SODALITE_TILES);
	public static final RegistryObject<Item> ELIXIS_SHARD = REGISTRY.register("elixis_shard", () -> new ElixisShardItem());
	public static final RegistryObject<Item> ELIXIS_UPGRADE_SMITHING_TEMPLATE = REGISTRY.register("elixis_upgrade_smithing_template", () -> new ElixisUpgradeSmithingTemplateItem());
	public static final RegistryObject<Item> ELIXITE_ARMOR_HELMET = REGISTRY.register("elixite_armor_helmet", () -> new ElixiteArmorItem.Helmet());
	public static final RegistryObject<Item> ELIXITE_ARMOR_CHESTPLATE = REGISTRY.register("elixite_armor_chestplate", () -> new ElixiteArmorItem.Chestplate());
	public static final RegistryObject<Item> ELIXITE_ARMOR_LEGGINGS = REGISTRY.register("elixite_armor_leggings", () -> new ElixiteArmorItem.Leggings());
	public static final RegistryObject<Item> ELIXITE_ARMOR_BOOTS = REGISTRY.register("elixite_armor_boots", () -> new ElixiteArmorItem.Boots());
	public static final RegistryObject<Item> CATECHISM_WING = REGISTRY.register("catechism_wing", () -> new CatechismWingItem());
	public static final RegistryObject<Item> INFUSION_TABLE = block(SovereignHorizonModBlocks.INFUSION_TABLE);
	public static final RegistryObject<Item> LARIMAR = block(SovereignHorizonModBlocks.LARIMAR);
	public static final RegistryObject<Item> LEPIDOLITE = block(SovereignHorizonModBlocks.LEPIDOLITE);
	public static final RegistryObject<Item> RIVED_GHAST_SPAWN_EGG = REGISTRY.register("rived_ghast_spawn_egg", () -> new ForgeSpawnEggItem(SovereignHorizonModEntities.RIVED_GHAST, -13395457, -39322, new Item.Properties()));
	public static final RegistryObject<Item> ASH = block(SovereignHorizonModBlocks.ASH);
	public static final RegistryObject<Item> SODALITE_QUARTZ_ORE = block(SovereignHorizonModBlocks.SODALITE_QUARTZ_ORE);
	public static final RegistryObject<Item> BLOCKOF_ELIXIS_SHARDS = block(SovereignHorizonModBlocks.BLOCKOF_ELIXIS_SHARDS);
	public static final RegistryObject<Item> SODALITE_EMERALD_ORE = block(SovereignHorizonModBlocks.SODALITE_EMERALD_ORE);
	public static final RegistryObject<Item> SODALITE_LAPIS_LAZULI_ORE = block(SovereignHorizonModBlocks.SODALITE_LAPIS_LAZULI_ORE);
	public static final RegistryObject<Item> SODALITE_REDSTONE_ORE = block(SovereignHorizonModBlocks.SODALITE_REDSTONE_ORE);
	public static final RegistryObject<Item> SODALITE_DIAMOND_ORE = block(SovereignHorizonModBlocks.SODALITE_DIAMOND_ORE);
	public static final RegistryObject<Item> THULITE = block(SovereignHorizonModBlocks.THULITE);
	public static final RegistryObject<Item> BLUESKIN = REGISTRY.register("blueskin", () -> new BlueskinItem());
	public static final RegistryObject<Item> MARBLE_STAIRS = block(SovereignHorizonModBlocks.MARBLE_STAIRS);
	public static final RegistryObject<Item> POLISHED_RAW_MARBLE_STAIRS = block(SovereignHorizonModBlocks.POLISHED_RAW_MARBLE_STAIRS);
	public static final RegistryObject<Item> MARBLE_BRICK_SLAB = block(SovereignHorizonModBlocks.MARBLE_BRICK_SLAB);
	public static final RegistryObject<Item> RAW_MARBLE_BRICK_SLAB = block(SovereignHorizonModBlocks.RAW_MARBLE_BRICK_SLAB);
	public static final RegistryObject<Item> POLISHED_MARBLE_WALL = block(SovereignHorizonModBlocks.POLISHED_MARBLE_WALL);
	public static final RegistryObject<Item> RAW_MARBLE_STAIRS = block(SovereignHorizonModBlocks.RAW_MARBLE_STAIRS);
	public static final RegistryObject<Item> RAW_MARBLE_BRICKS = block(SovereignHorizonModBlocks.RAW_MARBLE_BRICKS);
	public static final RegistryObject<Item> CRACKED_RAW_MARBLE_TILES = block(SovereignHorizonModBlocks.CRACKED_RAW_MARBLE_TILES);
	public static final RegistryObject<Item> RAW_MARBLE_SLAB = block(SovereignHorizonModBlocks.RAW_MARBLE_SLAB);
	public static final RegistryObject<Item> POLISHED_RAW_MARBLE_WALL = block(SovereignHorizonModBlocks.POLISHED_RAW_MARBLE_WALL);
	public static final RegistryObject<Item> MARBLE_TILE_WALL = block(SovereignHorizonModBlocks.MARBLE_TILE_WALL);
	public static final RegistryObject<Item> CRACKED_RAW_MARBLE_BRICKS = block(SovereignHorizonModBlocks.CRACKED_RAW_MARBLE_BRICKS);
	public static final RegistryObject<Item> RAW_MARBLE = block(SovereignHorizonModBlocks.RAW_MARBLE);
	public static final RegistryObject<Item> MARBLE_SLAB = block(SovereignHorizonModBlocks.MARBLE_SLAB);
	public static final RegistryObject<Item> RAW_MARBLE_PILLAR = block(SovereignHorizonModBlocks.RAW_MARBLE_PILLAR);
	public static final RegistryObject<Item> RAW_MARBLE_TILE_SLAB = block(SovereignHorizonModBlocks.RAW_MARBLE_TILE_SLAB);
	public static final RegistryObject<Item> POLISHED_MARBLE = block(SovereignHorizonModBlocks.POLISHED_MARBLE);
	public static final RegistryObject<Item> RAW_MARBLE_BRICK_STAIRS = block(SovereignHorizonModBlocks.RAW_MARBLE_BRICK_STAIRS);
	public static final RegistryObject<Item> POLISHED_MARBLE_STAIRS = block(SovereignHorizonModBlocks.POLISHED_MARBLE_STAIRS);
	public static final RegistryObject<Item> MARBLE_TILE_STAIRS = block(SovereignHorizonModBlocks.MARBLE_TILE_STAIRS);
	public static final RegistryObject<Item> CRACKED_MARBLE_TILES = block(SovereignHorizonModBlocks.CRACKED_MARBLE_TILES);
	public static final RegistryObject<Item> MARBLE_PILLAR = block(SovereignHorizonModBlocks.MARBLE_PILLAR);
	public static final RegistryObject<Item> MARBLE = block(SovereignHorizonModBlocks.MARBLE);
	public static final RegistryObject<Item> MARBLE_WALL = block(SovereignHorizonModBlocks.MARBLE_WALL);
	public static final RegistryObject<Item> POLISHED_MARBLE_SLAB = block(SovereignHorizonModBlocks.POLISHED_MARBLE_SLAB);
	public static final RegistryObject<Item> MARBLE_TILES = block(SovereignHorizonModBlocks.MARBLE_TILES);
	public static final RegistryObject<Item> RAW_MARBLE_TILE_STAIRS = block(SovereignHorizonModBlocks.RAW_MARBLE_TILE_STAIRS);
	public static final RegistryObject<Item> RAW_MARBLE_WALL = block(SovereignHorizonModBlocks.RAW_MARBLE_WALL);
	public static final RegistryObject<Item> RAW_MARBLE_BRICK_WALL = block(SovereignHorizonModBlocks.RAW_MARBLE_BRICK_WALL);
	public static final RegistryObject<Item> MARBLE_TILE_SLAB = block(SovereignHorizonModBlocks.MARBLE_TILE_SLAB);
	public static final RegistryObject<Item> POLISHED_RAW_MARBLE_SLAB = block(SovereignHorizonModBlocks.POLISHED_RAW_MARBLE_SLAB);
	public static final RegistryObject<Item> POLISHED_RAW_MARBLE = block(SovereignHorizonModBlocks.POLISHED_RAW_MARBLE);
	public static final RegistryObject<Item> MARBLE_BRICK_STAIRS = block(SovereignHorizonModBlocks.MARBLE_BRICK_STAIRS);
	public static final RegistryObject<Item> RAW_MARBLE_TILE_WALL = block(SovereignHorizonModBlocks.RAW_MARBLE_TILE_WALL);
	public static final RegistryObject<Item> MARBLE_BRICK_WALL = block(SovereignHorizonModBlocks.MARBLE_BRICK_WALL);
	public static final RegistryObject<Item> MARBLE_BRICKS = block(SovereignHorizonModBlocks.MARBLE_BRICKS);
	public static final RegistryObject<Item> CRACKED_MARBLE_BRICKS = block(SovereignHorizonModBlocks.CRACKED_MARBLE_BRICKS);
	public static final RegistryObject<Item> RAW_MARBLE_TILES = block(SovereignHorizonModBlocks.RAW_MARBLE_TILES);
	public static final RegistryObject<Item> LIQUID_VOID_BUCKET = REGISTRY.register("liquid_void_bucket", () -> new LiquidVoidItem());
	public static final RegistryObject<Item> REACHFLOWER = doubleBlock(SovereignHorizonModBlocks.REACHFLOWER);
	public static final RegistryObject<Item> DESOLATE_CREEPER_SPAWN_EGG = REGISTRY.register("desolate_creeper_spawn_egg", () -> new ForgeSpawnEggItem(SovereignHorizonModEntities.DESOLATE_CREEPER, -15509935, -12698289, new Item.Properties()));
	public static final RegistryObject<Item> DEPTH_SPROUT = block(SovereignHorizonModBlocks.DEPTH_SPROUT);
	public static final RegistryObject<Item> ELIXITE_GOLEM_SPAWN_EGG = REGISTRY.register("elixite_golem_spawn_egg", () -> new ForgeSpawnEggItem(SovereignHorizonModEntities.ELIXITE_GOLEM, -16711799, -6357048, new Item.Properties()));
	public static final RegistryObject<Item> CORRUPTED_PEARL = REGISTRY.register("corrupted_pearl", () -> new CorruptedPearlItem());
	public static final RegistryObject<Item> ELIXIS_CORRUPTED_ENDERMAN_SPAWN_EGG = REGISTRY.register("elixis_corrupted_enderman_spawn_egg",
			() -> new ForgeSpawnEggItem(SovereignHorizonModEntities.ELIXIS_CORRUPTED_ENDERMAN, -15000805, -14167645, new Item.Properties()));
	public static final RegistryObject<Item> ASHEN_FLOWER = block(SovereignHorizonModBlocks.ASHEN_FLOWER);
	public static final RegistryObject<Item> BLUESKIN_BOOTS_BOOTS = REGISTRY.register("blueskin_boots_boots", () -> new BlueskinBootsItem.Boots());
	public static final RegistryObject<Item> ASHY_FLESH = REGISTRY.register("ashy_flesh", () -> new AshyFleshItem());
	public static final RegistryObject<Item> SHORT_SPROUTS = block(SovereignHorizonModBlocks.SHORT_SPROUTS);
	public static final RegistryObject<Item> CREEPMINE = block(SovereignHorizonModBlocks.CREEPMINE);
	public static final RegistryObject<Item> TOTEMOF_CHANCE = REGISTRY.register("totemof_chance", () -> new TotemofChanceItem());
	public static final RegistryObject<Item> COOKED_CORRUPTED_FLESH = REGISTRY.register("cooked_corrupted_flesh", () -> new CookedCorruptedFleshItem());
	public static final RegistryObject<Item> GLOWWEED = block(SovereignHorizonModBlocks.GLOWWEED);
	public static final RegistryObject<Item> RAW_CORRUPTED_FLESH = REGISTRY.register("raw_corrupted_flesh", () -> new RawCorruptedFleshItem());
	public static final RegistryObject<Item> ASH_CRAWLER_SPAWN_EGG = REGISTRY.register("ash_crawler_spawn_egg", () -> new ForgeSpawnEggItem(SovereignHorizonModEntities.ASH_CRAWLER, -16777216, -15395563, new Item.Properties()));
	public static final RegistryObject<Item> RECORD_SUNRISE = REGISTRY.register("record_sunrise", () -> new RecordSunriseItem());
	public static final RegistryObject<Item> KEYSTONE = block(SovereignHorizonModBlocks.KEYSTONE);
	public static final RegistryObject<Item> SWITCHLING_SPAWN_EGG = REGISTRY.register("switchling_spawn_egg", () -> new ForgeSpawnEggItem(SovereignHorizonModEntities.SWITCHLING, -13369549, -16724992, new Item.Properties()));
	public static final RegistryObject<Item> BINARY_BRICK_WALL = block(SovereignHorizonModBlocks.BINARY_BRICK_WALL);
	public static final RegistryObject<Item> BINARY_GRATE = block(SovereignHorizonModBlocks.BINARY_GRATE);
	public static final RegistryObject<Item> BINARY_LAMP = block(SovereignHorizonModBlocks.BINARY_LAMP);
	public static final RegistryObject<Item> BINARY_SHARD = REGISTRY.register("binary_shard", () -> new BinaryShardItem());
	public static final RegistryObject<Item> CRACKED_BINARY_BRICKS = block(SovereignHorizonModBlocks.CRACKED_BINARY_BRICKS);
	public static final RegistryObject<Item> BINARY_BRICK_STAIRS = block(SovereignHorizonModBlocks.BINARY_BRICK_STAIRS);
	public static final RegistryObject<Item> BINARY_BRICKS = block(SovereignHorizonModBlocks.BINARY_BRICKS);
	public static final RegistryObject<Item> BINARY_BRICK_SLAB = block(SovereignHorizonModBlocks.BINARY_BRICK_SLAB);
	public static final RegistryObject<Item> KEYSTONE_WORKAROUND = block(SovereignHorizonModBlocks.KEYSTONE_WORKAROUND);
	public static final RegistryObject<Item> LARIMAR_STAIRS = block(SovereignHorizonModBlocks.LARIMAR_STAIRS);
	public static final RegistryObject<Item> LARIMAR_SLAB = block(SovereignHorizonModBlocks.LARIMAR_SLAB);
	public static final RegistryObject<Item> LARIMAR_WALL = block(SovereignHorizonModBlocks.LARIMAR_WALL);
	public static final RegistryObject<Item> POLISHED_LARIMAR = block(SovereignHorizonModBlocks.POLISHED_LARIMAR);
	public static final RegistryObject<Item> POLISHED_LARIMAR_STAIRS = block(SovereignHorizonModBlocks.POLISHED_LARIMAR_STAIRS);
	public static final RegistryObject<Item> POLISHED_LARIMAR_SLAB = block(SovereignHorizonModBlocks.POLISHED_LARIMAR_SLAB);
	public static final RegistryObject<Item> POLISHED_LARIMAR_WALL = block(SovereignHorizonModBlocks.POLISHED_LARIMAR_WALL);
	public static final RegistryObject<Item> LEPIDOLITE_STAIRS = block(SovereignHorizonModBlocks.LEPIDOLITE_STAIRS);
	public static final RegistryObject<Item> LEPIDOLITE_SLAB = block(SovereignHorizonModBlocks.LEPIDOLITE_SLAB);
	public static final RegistryObject<Item> LEPIDOLITE_WALL = block(SovereignHorizonModBlocks.LEPIDOLITE_WALL);
	public static final RegistryObject<Item> POLISHED_LEPIDOLITE = block(SovereignHorizonModBlocks.POLISHED_LEPIDOLITE);
	public static final RegistryObject<Item> POLISHED_LEPIDOLITE_STAIRS = block(SovereignHorizonModBlocks.POLISHED_LEPIDOLITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_LEPIDOLITE_SLAB = block(SovereignHorizonModBlocks.POLISHED_LEPIDOLITE_SLAB);
	public static final RegistryObject<Item> POLISHED_LEPIDOLITE_WALL = block(SovereignHorizonModBlocks.POLISHED_LEPIDOLITE_WALL);
	public static final RegistryObject<Item> THULITE_STAIRS = block(SovereignHorizonModBlocks.THULITE_STAIRS);
	public static final RegistryObject<Item> THULITE_SLAB = block(SovereignHorizonModBlocks.THULITE_SLAB);
	public static final RegistryObject<Item> THULITE_WALL = block(SovereignHorizonModBlocks.THULITE_WALL);
	public static final RegistryObject<Item> POLISHED_THULITE = block(SovereignHorizonModBlocks.POLISHED_THULITE);
	public static final RegistryObject<Item> POLISHED_THULITE_STAIRS = block(SovereignHorizonModBlocks.POLISHED_THULITE_STAIRS);
	public static final RegistryObject<Item> POLISHED_THULITE_SLAB = block(SovereignHorizonModBlocks.POLISHED_THULITE_SLAB);
	public static final RegistryObject<Item> POLISHED_THULITE_WALL = block(SovereignHorizonModBlocks.POLISHED_THULITE_WALL);
	public static final RegistryObject<Item> ERROR_PEARL = REGISTRY.register("error_pearl", () -> new ErrorPearlItem());
	public static final RegistryObject<Item> TEST_STAIRS = block(SovereignHorizonModBlocks.TEST_STAIRS);
	public static final RegistryObject<Item> TEST_SLAB = block(SovereignHorizonModBlocks.TEST_SLAB);
	public static final RegistryObject<Item> TEST_WALL = block(SovereignHorizonModBlocks.TEST_WALL);
	public static final RegistryObject<Item> SODALITEAND_LEPIDOLITE_TILE_STAIRS = block(SovereignHorizonModBlocks.SODALITEAND_LEPIDOLITE_TILE_STAIRS);
	public static final RegistryObject<Item> SODALITEAND_LEPIDOLITE_TILE_SLAB = block(SovereignHorizonModBlocks.SODALITEAND_LEPIDOLITE_TILE_SLAB);
	public static final RegistryObject<Item> SODALITEAND_LEPIDOLITE_TILES = block(SovereignHorizonModBlocks.SODALITEAND_LEPIDOLITE_TILES);
	public static final RegistryObject<Item> SODALITEAND_LEPIDOLITE_TILE_WALL = block(SovereignHorizonModBlocks.SODALITEAND_LEPIDOLITE_TILE_WALL);
	public static final RegistryObject<Item> BLOOD_ROSE = block(SovereignHorizonModBlocks.BLOOD_ROSE);
	public static final RegistryObject<Item> SODALITEAND_THULITE_TILE_STAIRS = block(SovereignHorizonModBlocks.SODALITEAND_THULITE_TILE_STAIRS);
	public static final RegistryObject<Item> SODALITEAND_THULITE_TILE_SLAB = block(SovereignHorizonModBlocks.SODALITEAND_THULITE_TILE_SLAB);
	public static final RegistryObject<Item> SODALITEAND_THULITE_TILES = block(SovereignHorizonModBlocks.SODALITEAND_THULITE_TILES);
	public static final RegistryObject<Item> SODALITEAND_THULITE_TILE_WALL = block(SovereignHorizonModBlocks.SODALITEAND_THULITE_TILE_WALL);
	public static final RegistryObject<Item> MARBLEAND_THULITE_TILE_STAIRS = block(SovereignHorizonModBlocks.MARBLEAND_THULITE_TILE_STAIRS);
	public static final RegistryObject<Item> MARBLEAND_THULITE_TILE_SLAB = block(SovereignHorizonModBlocks.MARBLEAND_THULITE_TILE_SLAB);
	public static final RegistryObject<Item> MARBLEAND_THULITE_TILES = block(SovereignHorizonModBlocks.MARBLEAND_THULITE_TILES);
	public static final RegistryObject<Item> MARBLEAND_THULITE_TILE_WALL = block(SovereignHorizonModBlocks.MARBLEAND_THULITE_TILE_WALL);
	public static final RegistryObject<Item> MARBLEAND_SODALITE_TILE_STAIRS = block(SovereignHorizonModBlocks.MARBLEAND_SODALITE_TILE_STAIRS);
	public static final RegistryObject<Item> MARBLEAND_SODALITE_TILE_SLAB = block(SovereignHorizonModBlocks.MARBLEAND_SODALITE_TILE_SLAB);
	public static final RegistryObject<Item> MARBLEAND_SODALITE_TILES = block(SovereignHorizonModBlocks.MARBLEAND_SODALITE_TILES);
	public static final RegistryObject<Item> MARBLEAND_SODALITE_TILE_WALL = block(SovereignHorizonModBlocks.MARBLEAND_SODALITE_TILE_WALL);
	public static final RegistryObject<Item> THULITEAND_LEPIDOLITE_TILE_STAIRS = block(SovereignHorizonModBlocks.THULITEAND_LEPIDOLITE_TILE_STAIRS);
	public static final RegistryObject<Item> THULITEAND_LEPIDOLITE_TILE_SLAB = block(SovereignHorizonModBlocks.THULITEAND_LEPIDOLITE_TILE_SLAB);
	public static final RegistryObject<Item> THULITEAND_LEPIDOLITE_TILES = block(SovereignHorizonModBlocks.THULITEAND_LEPIDOLITE_TILES);
	public static final RegistryObject<Item> THULITEAND_LEPIDOLITE_TILE_WALL = block(SovereignHorizonModBlocks.THULITEAND_LEPIDOLITE_TILE_WALL);
	public static final RegistryObject<Item> MARBLEAND_LEPIDOLITE_TILE_STAIRS = block(SovereignHorizonModBlocks.MARBLEAND_LEPIDOLITE_TILE_STAIRS);
	public static final RegistryObject<Item> MARBLEAND_LEPIDOLITE_TILE_SLAB = block(SovereignHorizonModBlocks.MARBLEAND_LEPIDOLITE_TILE_SLAB);
	public static final RegistryObject<Item> MARBLEAND_LEPIDOLITE_TILES = block(SovereignHorizonModBlocks.MARBLEAND_LEPIDOLITE_TILES);
	public static final RegistryObject<Item> MARBLEAND_LEPIDOLITE_TILE_WALL = block(SovereignHorizonModBlocks.MARBLEAND_LEPIDOLITE_TILE_WALL);
	public static final RegistryObject<Item> SOLID_VOID = block(SovereignHorizonModBlocks.SOLID_VOID);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
